# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_mapping.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'event_mapping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65vent_mapping.proto\x12\x06\x65vents\"Z\n\x0bInstruction\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.events.InstructionType\x12\x0e\n\x06params\x18\x02 \x03(\x05\x12\x14\n\x0cstringParams\x18\x03 \x03(\t\"=\n\x11\x43onditionalReturn\x12\x13\n\x0bpassedEvIds\x18\x01 \x03(\x05\x12\x13\n\x0breturnValue\x18\x02 \x01(\x05\"\xdb\x01\n\x0c\x45ventMapping\x12\x0c\n\x04\x65vId\x18\x01 \x01(\x05\x12\r\n\x05\x66lag1\x18\x02 \x01(\x08\x12\x0e\n\x06\x65vFunc\x18\x03 \x01(\t\x12)\n\x0cinstructions\x18\x04 \x03(\x0b\x32\x13.events.Instruction\x12\x35\n\x12\x63onditionalReturns\x18\x05 \x03(\x0b\x32\x19.events.ConditionalReturn\x12\x14\n\x0creturnValues\x18\x06 \x03(\x05\x12\x12\n\nhasChoices\x18\x07 \x01(\x08\x12\x12\n\nfromEvents\x18\x08 \x03(\x05\"G\n\rEventMappings\x12\x10\n\x08textPool\x18\x02 \x03(\t\x12$\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x14.events.EventMapping*\xc6\x02\n\x0fInstructionType\x12\x0e\n\nPlayDialog\x10\x00\x12\x10\n\x0cShowDecision\x10\x01\x12\x0b\n\x07PlayBgm\x10\x02\x12\n\n\x06PlaySe\x10\x03\x12\x0c\n\x08SetBgImg\x10\x04\x12\x0f\n\x0bSetCharaImg\x10\x05\x12\x0f\n\x0bShakeScreen\x10\x06\x12\x18\n\x14TransitionToGraphics\x10\x07\x12\x1c\n\x18TransitionToGraphicsFade\x10\x08\x12\n\n\x06ShowCg\x10\t\x12\x15\n\x11\x46\x61\x64\x65SystemToBlack\x10\n\x12\x14\n\x10SetGraphicsState\x10\x0b\x12\x16\n\x12ToggleGraphicsFlag\x10\x0c\x12\x10\n\x0c\x41utoContinue\x10\r\x12\r\n\tIncMemory\x10\x0e\x12\x0e\n\nShowStaffA\x10\x0f\x12\x0e\n\nShowStaffB\x10\x10\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_mapping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSTRUCTIONTYPE']._serialized_start=482
  _globals['_INSTRUCTIONTYPE']._serialized_end=808
  _globals['_INSTRUCTION']._serialized_start=31
  _globals['_INSTRUCTION']._serialized_end=121
  _globals['_CONDITIONALRETURN']._serialized_start=123
  _globals['_CONDITIONALRETURN']._serialized_end=184
  _globals['_EVENTMAPPING']._serialized_start=187
  _globals['_EVENTMAPPING']._serialized_end=406
  _globals['_EVENTMAPPINGS']._serialized_start=408
  _globals['_EVENTMAPPINGS']._serialized_end=479
# @@protoc_insertion_point(module_scope)
