// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: event_mapping.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EventMapping {

  /// <summary>Holder for reflection information generated from event_mapping.proto</summary>
  public static partial class EventMappingReflection {

    #region Descriptor
    /// <summary>File descriptor for event_mapping.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventMappingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNldmVudF9tYXBwaW5nLnByb3RvEg1ldmVudF9tYXBwaW5nImIKC0luc3Ry",
            "dWN0aW9uEiwKBHR5cGUYASABKA4yHi5ldmVudF9tYXBwaW5nLkluc3RydWN0",
            "aW9uVHlwZRIOCgZwYXJhbXMYAiADKAUSFQoNc3RyaW5nX3BhcmFtcxgDIAMo",
            "CSKqAQoMRXZlbnRNYXBwaW5nEgwKBGV2SWQYASABKAUSDQoFZmxhZzEYAiAB",
            "KAgSDgoGZXZGdW5jGAMgASgJEg8KB2FkZHJlc3MYBCABKAUSMAoMaW5zdHJ1",
            "Y3Rpb25zGAUgAygLMhouZXZlbnRfbWFwcGluZy5JbnN0cnVjdGlvbhIVCg1y",
            "ZXR1cm5fdmFsdWVzGAYgAygFEhMKC2hhc19jaG9pY2VzGAcgASgIIk8KDUV2",
            "ZW50TWFwcGluZ3MSEQoJdGV4dF9wb29sGAEgAygJEisKBmV2ZW50cxgCIAMo",
            "CzIbLmV2ZW50X21hcHBpbmcuRXZlbnRNYXBwaW5nKtMDCg9JbnN0cnVjdGlv",
            "blR5cGUSFAoQUExBWV9ESUFMT0dfQUREUhAAEhYKElNIT1dfREVDSVNJT05f",
            "QUREUhABEhEKDVBMQVlfQkdNX0FERFIQAhIQCgxQTEFZX1NFX0FERFIQAxIT",
            "Cg9TRVRfQkdfSU1HX0FERFIQBBIWChJTRVRfQ0hBUkFfSU1HX0FERFIQBRIW",
            "ChJTTEVFUF9PUl9GQURFX0FERFIQBhIfChtUUkFOU0lUSU9OX1RPX0dSQVBI",
            "SUNTX0FERFIQBxIkCiBUUkFOU0lUSU9OX1RPX0dSQVBISUNTX0ZBREVfQURE",
            "UhAIEhAKDFNIT1dfQ0dfQUREUhAJEh0KGUZBREVfU1lTVEVNX1RPX0JMQUNL",
            "X0FERFIQChIbChdTRVRfR1JBUEhJQ1NfU1RBVEVfQUREUhALEh0KGVRPR0dM",
            "RV9HUkFQSElDU19GTEFHX0FERFIQDBIVChFTSEFLRV9TQ1JFRU5fQUREUhAN",
            "EhcKE0dFVF9USUNLX0NPVU5UX0FERFIQDhIWChJUT0dHTEVfU1RBRkZfU1RB",
            "VEUQDxIVChFTSE9XX1NUQUZGX0FfQUREUhAQEhUKEVNIT1dfU1RBRkZfQl9B",
            "RERSEBFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EventMapping.InstructionType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EventMapping.Instruction), global::EventMapping.Instruction.Parser, new[]{ "Type", "Params", "StringParams" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EventMapping.EventMapping), global::EventMapping.EventMapping.Parser, new[]{ "EvId", "Flag1", "EvFunc", "Address", "Instructions", "ReturnValues", "HasChoices" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EventMapping.EventMappings), global::EventMapping.EventMappings.Parser, new[]{ "TextPool", "Events" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum InstructionType {
    [pbr::OriginalName("PLAY_DIALOG_ADDR")] PlayDialogAddr = 0,
    [pbr::OriginalName("SHOW_DECISION_ADDR")] ShowDecisionAddr = 1,
    [pbr::OriginalName("PLAY_BGM_ADDR")] PlayBgmAddr = 2,
    [pbr::OriginalName("PLAY_SE_ADDR")] PlaySeAddr = 3,
    [pbr::OriginalName("SET_BG_IMG_ADDR")] SetBgImgAddr = 4,
    [pbr::OriginalName("SET_CHARA_IMG_ADDR")] SetCharaImgAddr = 5,
    [pbr::OriginalName("SLEEP_OR_FADE_ADDR")] SleepOrFadeAddr = 6,
    [pbr::OriginalName("TRANSITION_TO_GRAPHICS_ADDR")] TransitionToGraphicsAddr = 7,
    [pbr::OriginalName("TRANSITION_TO_GRAPHICS_FADE_ADDR")] TransitionToGraphicsFadeAddr = 8,
    [pbr::OriginalName("SHOW_CG_ADDR")] ShowCgAddr = 9,
    [pbr::OriginalName("FADE_SYSTEM_TO_BLACK_ADDR")] FadeSystemToBlackAddr = 10,
    [pbr::OriginalName("SET_GRAPHICS_STATE_ADDR")] SetGraphicsStateAddr = 11,
    [pbr::OriginalName("TOGGLE_GRAPHICS_FLAG_ADDR")] ToggleGraphicsFlagAddr = 12,
    [pbr::OriginalName("SHAKE_SCREEN_ADDR")] ShakeScreenAddr = 13,
    [pbr::OriginalName("GET_TICK_COUNT_ADDR")] GetTickCountAddr = 14,
    [pbr::OriginalName("TOGGLE_STAFF_STATE")] ToggleStaffState = 15,
    [pbr::OriginalName("SHOW_STAFF_A_ADDR")] ShowStaffAAddr = 16,
    [pbr::OriginalName("SHOW_STAFF_B_ADDR")] ShowStaffBAddr = 17,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Instruction : pb::IMessage<Instruction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Instruction> _parser = new pb::MessageParser<Instruction>(() => new Instruction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Instruction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EventMapping.EventMappingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Instruction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Instruction(Instruction other) : this() {
      type_ = other.type_;
      params_ = other.params_.Clone();
      stringParams_ = other.stringParams_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Instruction Clone() {
      return new Instruction(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::EventMapping.InstructionType type_ = global::EventMapping.InstructionType.PlayDialogAddr;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EventMapping.InstructionType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_params_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> params_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Params {
      get { return params_; }
    }

    /// <summary>Field number for the "string_params" field.</summary>
    public const int StringParamsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_stringParams_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> stringParams_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> StringParams {
      get { return stringParams_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Instruction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Instruction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if(!params_.Equals(other.params_)) return false;
      if(!stringParams_.Equals(other.stringParams_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::EventMapping.InstructionType.PlayDialogAddr) hash ^= Type.GetHashCode();
      hash ^= params_.GetHashCode();
      hash ^= stringParams_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::EventMapping.InstructionType.PlayDialogAddr) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      params_.WriteTo(output, _repeated_params_codec);
      stringParams_.WriteTo(output, _repeated_stringParams_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::EventMapping.InstructionType.PlayDialogAddr) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      params_.WriteTo(ref output, _repeated_params_codec);
      stringParams_.WriteTo(ref output, _repeated_stringParams_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::EventMapping.InstructionType.PlayDialogAddr) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += params_.CalculateSize(_repeated_params_codec);
      size += stringParams_.CalculateSize(_repeated_stringParams_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Instruction other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::EventMapping.InstructionType.PlayDialogAddr) {
        Type = other.Type;
      }
      params_.Add(other.params_);
      stringParams_.Add(other.stringParams_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::EventMapping.InstructionType) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
          case 26: {
            stringParams_.AddEntriesFrom(input, _repeated_stringParams_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::EventMapping.InstructionType) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            params_.AddEntriesFrom(ref input, _repeated_params_codec);
            break;
          }
          case 26: {
            stringParams_.AddEntriesFrom(ref input, _repeated_stringParams_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EventMapping : pb::IMessage<EventMapping>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventMapping> _parser = new pb::MessageParser<EventMapping>(() => new EventMapping());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EventMapping> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EventMapping.EventMappingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventMapping() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventMapping(EventMapping other) : this() {
      evId_ = other.evId_;
      flag1_ = other.flag1_;
      evFunc_ = other.evFunc_;
      address_ = other.address_;
      instructions_ = other.instructions_.Clone();
      returnValues_ = other.returnValues_.Clone();
      hasChoices_ = other.hasChoices_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventMapping Clone() {
      return new EventMapping(this);
    }

    /// <summary>Field number for the "evId" field.</summary>
    public const int EvIdFieldNumber = 1;
    private int evId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EvId {
      get { return evId_; }
      set {
        evId_ = value;
      }
    }

    /// <summary>Field number for the "flag1" field.</summary>
    public const int Flag1FieldNumber = 2;
    private bool flag1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Flag1 {
      get { return flag1_; }
      set {
        flag1_ = value;
      }
    }

    /// <summary>Field number for the "evFunc" field.</summary>
    public const int EvFuncFieldNumber = 3;
    private string evFunc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EvFunc {
      get { return evFunc_; }
      set {
        evFunc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 4;
    private int address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    /// <summary>Field number for the "instructions" field.</summary>
    public const int InstructionsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::EventMapping.Instruction> _repeated_instructions_codec
        = pb::FieldCodec.ForMessage(42, global::EventMapping.Instruction.Parser);
    private readonly pbc::RepeatedField<global::EventMapping.Instruction> instructions_ = new pbc::RepeatedField<global::EventMapping.Instruction>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EventMapping.Instruction> Instructions {
      get { return instructions_; }
    }

    /// <summary>Field number for the "return_values" field.</summary>
    public const int ReturnValuesFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_returnValues_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> returnValues_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> ReturnValues {
      get { return returnValues_; }
    }

    /// <summary>Field number for the "has_choices" field.</summary>
    public const int HasChoicesFieldNumber = 7;
    private bool hasChoices_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasChoices {
      get { return hasChoices_; }
      set {
        hasChoices_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EventMapping);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EventMapping other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EvId != other.EvId) return false;
      if (Flag1 != other.Flag1) return false;
      if (EvFunc != other.EvFunc) return false;
      if (Address != other.Address) return false;
      if(!instructions_.Equals(other.instructions_)) return false;
      if(!returnValues_.Equals(other.returnValues_)) return false;
      if (HasChoices != other.HasChoices) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EvId != 0) hash ^= EvId.GetHashCode();
      if (Flag1 != false) hash ^= Flag1.GetHashCode();
      if (EvFunc.Length != 0) hash ^= EvFunc.GetHashCode();
      if (Address != 0) hash ^= Address.GetHashCode();
      hash ^= instructions_.GetHashCode();
      hash ^= returnValues_.GetHashCode();
      if (HasChoices != false) hash ^= HasChoices.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EvId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EvId);
      }
      if (Flag1 != false) {
        output.WriteRawTag(16);
        output.WriteBool(Flag1);
      }
      if (EvFunc.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EvFunc);
      }
      if (Address != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Address);
      }
      instructions_.WriteTo(output, _repeated_instructions_codec);
      returnValues_.WriteTo(output, _repeated_returnValues_codec);
      if (HasChoices != false) {
        output.WriteRawTag(56);
        output.WriteBool(HasChoices);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EvId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EvId);
      }
      if (Flag1 != false) {
        output.WriteRawTag(16);
        output.WriteBool(Flag1);
      }
      if (EvFunc.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EvFunc);
      }
      if (Address != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Address);
      }
      instructions_.WriteTo(ref output, _repeated_instructions_codec);
      returnValues_.WriteTo(ref output, _repeated_returnValues_codec);
      if (HasChoices != false) {
        output.WriteRawTag(56);
        output.WriteBool(HasChoices);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EvId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EvId);
      }
      if (Flag1 != false) {
        size += 1 + 1;
      }
      if (EvFunc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EvFunc);
      }
      if (Address != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Address);
      }
      size += instructions_.CalculateSize(_repeated_instructions_codec);
      size += returnValues_.CalculateSize(_repeated_returnValues_codec);
      if (HasChoices != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EventMapping other) {
      if (other == null) {
        return;
      }
      if (other.EvId != 0) {
        EvId = other.EvId;
      }
      if (other.Flag1 != false) {
        Flag1 = other.Flag1;
      }
      if (other.EvFunc.Length != 0) {
        EvFunc = other.EvFunc;
      }
      if (other.Address != 0) {
        Address = other.Address;
      }
      instructions_.Add(other.instructions_);
      returnValues_.Add(other.returnValues_);
      if (other.HasChoices != false) {
        HasChoices = other.HasChoices;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EvId = input.ReadInt32();
            break;
          }
          case 16: {
            Flag1 = input.ReadBool();
            break;
          }
          case 26: {
            EvFunc = input.ReadString();
            break;
          }
          case 32: {
            Address = input.ReadInt32();
            break;
          }
          case 42: {
            instructions_.AddEntriesFrom(input, _repeated_instructions_codec);
            break;
          }
          case 50:
          case 48: {
            returnValues_.AddEntriesFrom(input, _repeated_returnValues_codec);
            break;
          }
          case 56: {
            HasChoices = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EvId = input.ReadInt32();
            break;
          }
          case 16: {
            Flag1 = input.ReadBool();
            break;
          }
          case 26: {
            EvFunc = input.ReadString();
            break;
          }
          case 32: {
            Address = input.ReadInt32();
            break;
          }
          case 42: {
            instructions_.AddEntriesFrom(ref input, _repeated_instructions_codec);
            break;
          }
          case 50:
          case 48: {
            returnValues_.AddEntriesFrom(ref input, _repeated_returnValues_codec);
            break;
          }
          case 56: {
            HasChoices = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EventMappings : pb::IMessage<EventMappings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventMappings> _parser = new pb::MessageParser<EventMappings>(() => new EventMappings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EventMappings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EventMapping.EventMappingReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventMappings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventMappings(EventMappings other) : this() {
      textPool_ = other.textPool_.Clone();
      events_ = other.events_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventMappings Clone() {
      return new EventMappings(this);
    }

    /// <summary>Field number for the "text_pool" field.</summary>
    public const int TextPoolFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_textPool_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> textPool_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> TextPool {
      get { return textPool_; }
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::EventMapping.EventMapping> _repeated_events_codec
        = pb::FieldCodec.ForMessage(18, global::EventMapping.EventMapping.Parser);
    private readonly pbc::RepeatedField<global::EventMapping.EventMapping> events_ = new pbc::RepeatedField<global::EventMapping.EventMapping>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EventMapping.EventMapping> Events {
      get { return events_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EventMappings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EventMappings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!textPool_.Equals(other.textPool_)) return false;
      if(!events_.Equals(other.events_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= textPool_.GetHashCode();
      hash ^= events_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      textPool_.WriteTo(output, _repeated_textPool_codec);
      events_.WriteTo(output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      textPool_.WriteTo(ref output, _repeated_textPool_codec);
      events_.WriteTo(ref output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += textPool_.CalculateSize(_repeated_textPool_codec);
      size += events_.CalculateSize(_repeated_events_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EventMappings other) {
      if (other == null) {
        return;
      }
      textPool_.Add(other.textPool_);
      events_.Add(other.events_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            textPool_.AddEntriesFrom(input, _repeated_textPool_codec);
            break;
          }
          case 18: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            textPool_.AddEntriesFrom(ref input, _repeated_textPool_codec);
            break;
          }
          case 18: {
            events_.AddEntriesFrom(ref input, _repeated_events_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
