# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_mapping.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'event_mapping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65vent_mapping.proto\x12\revent_mapping\"b\n\x0bInstruction\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.event_mapping.InstructionType\x12\x0e\n\x06params\x18\x02 \x03(\x05\x12\x15\n\rstring_params\x18\x03 \x03(\t\"\x99\x01\n\x0c\x45ventMapping\x12\x0c\n\x04\x65vId\x18\x01 \x01(\x05\x12\r\n\x05\x66lag1\x18\x02 \x01(\x08\x12\x0e\n\x06\x65vFunc\x18\x03 \x01(\t\x12\x30\n\x0cinstructions\x18\x04 \x03(\x0b\x32\x1a.event_mapping.Instruction\x12\x15\n\rreturn_values\x18\x05 \x03(\x05\x12\x13\n\x0bhas_choices\x18\x06 \x01(\x08\"O\n\rEventMappings\x12\x11\n\ttext_pool\x18\x01 \x03(\t\x12+\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x1b.event_mapping.EventMapping*\xba\x03\n\x0fInstructionType\x12\x14\n\x10PLAY_DIALOG_ADDR\x10\x00\x12\x16\n\x12SHOW_DECISION_ADDR\x10\x01\x12\x11\n\rPLAY_BGM_ADDR\x10\x02\x12\x10\n\x0cPLAY_SE_ADDR\x10\x03\x12\x13\n\x0fSET_BG_IMG_ADDR\x10\x04\x12\x16\n\x12SET_CHARA_IMG_ADDR\x10\x05\x12\x16\n\x12SLEEP_OR_FADE_ADDR\x10\x06\x12\x1f\n\x1bTRANSITION_TO_GRAPHICS_ADDR\x10\x07\x12$\n TRANSITION_TO_GRAPHICS_FADE_ADDR\x10\x08\x12\x10\n\x0cSHOW_CG_ADDR\x10\t\x12\x1d\n\x19\x46\x41\x44\x45_SYSTEM_TO_BLACK_ADDR\x10\n\x12\x1b\n\x17SET_GRAPHICS_STATE_ADDR\x10\x0b\x12\x1d\n\x19TOGGLE_GRAPHICS_FLAG_ADDR\x10\x0c\x12\x15\n\x11SHAKE_SCREEN_ADDR\x10\r\x12\x16\n\x12TOGGLE_STAFF_STATE\x10\x0e\x12\x15\n\x11SHOW_STAFF_A_ADDR\x10\x0f\x12\x15\n\x11SHOW_STAFF_B_ADDR\x10\x10\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_mapping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSTRUCTIONTYPE']._serialized_start=376
  _globals['_INSTRUCTIONTYPE']._serialized_end=818
  _globals['_INSTRUCTION']._serialized_start=38
  _globals['_INSTRUCTION']._serialized_end=136
  _globals['_EVENTMAPPING']._serialized_start=139
  _globals['_EVENTMAPPING']._serialized_end=292
  _globals['_EVENTMAPPINGS']._serialized_start=294
  _globals['_EVENTMAPPINGS']._serialized_end=373
# @@protoc_insertion_point(module_scope)
