# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_mapping.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'voice_mapping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13voice_mapping.proto\x12\rvoice_mapping\"9\n\tVoiceInfo\x12\x0c\n\x04\x62\x61nk\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x02\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\"\x1b\n\x0bPreloadInfo\x12\x0c\n\x04\x62\x61nk\x18\x02 \x03(\t\"\xbe\x02\n\rVoiceMappings\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x38\n\x06voices\x18\x02 \x03(\x0b\x32(.voice_mapping.VoiceMappings.VoicesEntry\x12G\n\x0epreload_blocks\x18\x03 \x03(\x0b\x32/.voice_mapping.VoiceMappings.PreloadBlocksEntry\x1aG\n\x0bVoicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.voice_mapping.VoiceInfo:\x02\x38\x01\x1aP\n\x12PreloadBlocksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.voice_mapping.PreloadInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_mapping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOICEMAPPINGS_VOICESENTRY']._loaded_options = None
  _globals['_VOICEMAPPINGS_VOICESENTRY']._serialized_options = b'8\001'
  _globals['_VOICEMAPPINGS_PRELOADBLOCKSENTRY']._loaded_options = None
  _globals['_VOICEMAPPINGS_PRELOADBLOCKSENTRY']._serialized_options = b'8\001'
  _globals['_VOICEINFO']._serialized_start=38
  _globals['_VOICEINFO']._serialized_end=95
  _globals['_PRELOADINFO']._serialized_start=97
  _globals['_PRELOADINFO']._serialized_end=124
  _globals['_VOICEMAPPINGS']._serialized_start=127
  _globals['_VOICEMAPPINGS']._serialized_end=445
  _globals['_VOICEMAPPINGS_VOICESENTRY']._serialized_start=292
  _globals['_VOICEMAPPINGS_VOICESENTRY']._serialized_end=363
  _globals['_VOICEMAPPINGS_PRELOADBLOCKSENTRY']._serialized_start=365
  _globals['_VOICEMAPPINGS_PRELOADBLOCKSENTRY']._serialized_end=445
# @@protoc_insertion_point(module_scope)
